name: Build genpattern - Linux

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create build and artifact directories
        run: |
          mkdir -p build
          mkdir -p artifact

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', 'docker/**') }}

      - name: Build Docker builder image
        run: docker build . -t gp_cpp_builder

      - name: Build and test CMake project in Docker
        run: docker run --rm -v "$(pwd):/app" gp_cpp_builder

      - name: Copy SO for Linux
        run: cp build/gp_cpp/libgenpattern.so artifact/

      - name: Upload Linux build artifact (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: genpattern_linux_x86_64
          path: artifact/