name: Build and Release genpattern

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux_x86_64
            runsOn: ubuntu-24.04
            artifact_name: genpattern_linux_x86_64
          - platform: linux_arm64
            runsOn: ubuntu-24.04-arm
            artifact_name: genpattern_linux_arm64
          - platform: windows
            runsOn: windows-latest
            artifact_name: genpattern_windows_x86_64
    runs-on: ${{ matrix.runsOn }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build genpattern on Linux
        if: matrix.platform != 'windows'
        uses: ./.github/actions/build-genpattern-linux
        with:
          artifact_name: ${{ matrix.artifact_name }}

      - name: Build genpattern on Windows
        if: matrix.platform == 'windows'
        uses: ./.github/actions/build-genpattern-windows
        with:
          artifact_name: ${{ matrix.artifact_name }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: genpattern_windows_x86_64

      - name: Download Linux x86_64 build artifact
        uses: actions/download-artifact@v4
        with:
          name: genpattern_linux_x86_64

      - name: Download Linux arm64 build artifact
        uses: actions/download-artifact@v4
        with:
          name: genpattern_linux_arm64

      - name: Create Windows ZIP
        run: zip -j genpattern.windows.x64.zip genpattern_windows_x86_64/genpattern.dll
        shell: bash

      - name: Create Linux x86_64 tar.gz
        run: tar -czvf genpattern.linux.x86_64.tar.gz -C genpattern_linux_x86_64 libgenpattern.so
        shell: bash

      - name: Create Linux arm64 tar.gz
        run: tar -czvf genpattern.linux.arm64.tar.gz -C genpattern_linux_arm64 libgenpattern.so
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref }}"
          body: "Automatically created release for ${{ github.ref }}"
          files: |
            genpattern.windows.x64.zip
            genpattern.linux.x86_64.tar.gz
            genpattern.linux.arm64.tar.gz
