name: Build genpattern

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Create build directory
        run: if (!(Test-Path "build")) { New-Item -ItemType directory -Path build }
        shell: pwsh

      - name: Cache vcpkg_installed
        uses: actions/cache@v4
        with:
          path: build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-

      - name: Configure CMake project
        run: |
          cmake -S . -B build `
            -DBUILD_TESTS=ON `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_GENERATOR_TOOLSET=ClangCL `
            -DCMAKE_TOOLCHAIN_FILE="${env:VCPKG_INSTALLATION_ROOT}\scripts\buildsystems\vcpkg.cmake"
        shell: pwsh
        timeout-minutes: 30

      - name: Build CMake project
        run: cmake --build build --config Release
        timeout-minutes: 30

      - name: Run tests
        run: ctest --test-dir build -C Release
        timeout-minutes: 15

      - name: Copy DLL for Windows
        run: |
            if (!(Test-Path artifact)) { New-Item -ItemType directory -Path artifact }; `
            cp build/gp_cpp/Release/genpattern.dll artifact/
      
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', 'docker/**') }}

      - name: Build Docker builder image
        run: docker build . -t gp_cpp_builder

      - name: Build and test CMake project in Docker
        run: docker run --rm -v "$($PWD.Path):/app" gp_cpp_builder
        
      - name: Copy SO for Linux
        run: cp build/gp_cpp/libgenpattern.so artifact/
      
      - name: Upload build artifact (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: genpattern_build_x86_64
          path: artifact/
